repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    version: latest
    values:
      - replicaCount: 5
      - image:
          tag: 3.5.2
      - auth:
          clientProtocol: SASL_PLAINTEXT
          interBrokerProtocol: SASL_PLAINTEXT

  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    version: latest
    values:
      - replicaCount: 1
      - auth:
          enabled: false
          clientProtocol: PLAINTEXT
          interBrokerProtocol: PLAINTEXT
