apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://127.0.0.1:6443
    insecure-skip-tls-verify: true
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: cd
    namespace: homework
  name: cd
current-context: cd
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5YZEplTFNyX1FGeW1IeEMtOFN5V1NfOUhvVjZxVk5MbkJXQ2ZQc2hLYjgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzMzNjU0NDMzLCJpYXQiOjE3MzM1NjgwMzMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYzdmOTI5YTYtOTdhMi00NDFjLTk0ZDYtMjNjMGM3YjE5ZmZlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6IjNiOTE2OTU0LTUzZDgtNDdjNi1hZGVmLTUxNjE4NzRhZmRjZiJ9fSwibmJmIjoxNzMzNTY4MDMzLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.g9vmbkTRYU6j58MXPd7RBk5xPX0pzuZq1uYYjW4q5u3GIZccQI6TNUWakkI_9hntcxQGEHzS88btKMb6UCaPIFXKDDl23NgGAuQIR7DDH7fgazF35ocLvHjRBWv87x5-aE0D_-Y0xlm60KVKf5guprV-UwUcVos49WbDzRONwO67_gb5aXnLlESC6BbHxmQSCv0PSMW5ijqWDtfSqtGVp2vL4tcI60uRuwfIQREaIG1xH6Ep1o6SD2YzXaMJb5-c5hAmky-BsBqL6xfZuLHausuADmxepl1Aa9syw0iytu22vAWo4s3tsvqNmjTEMB-rLe6Hf-kA4Pq5NwuaarzF-Q
