apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework-app
  template:
    metadata:
      labels:
        app: homework-app
    spec:
      volumes:
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: homework-pvc
      - name: config-volume
        configMap:
          name: homework-configmap
      initContainers:
      - name: init-container
        image: busybox
        command: ["sh", "-c"]
        args:
          - wget -O /pvc/index.html https://example.com && echo "Downloaded index.html";
        volumeMounts:
        - name: pvc-volume
          mountPath: /pvc
      containers:
      - name: main-container
        image: nginx
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c", "echo 'server { listen 8000; root /homework; index index.html; }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
        volumeMounts:
        - name: pvc-volume
          mountPath: /homework
        - name: config-volume
          mountPath: /homework/conf
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
