apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
      - name: shared-volume
        emptyDir: {}
      initContainers:
      - name: init-container
        image: busybox
        command: ["sh", "-c"]
        args:
          - wget -O /init/index.html https://example.com &&
            echo "Downloaded index.html";
        volumeMounts:
        - name: shared-volume
          mountPath: /init
      containers:
      - name: main-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: shared-volume
          mountPath: /homework
        readinessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
        command:
        - /bin/sh
        - -c
        - |
          echo 'server {
            listen 8000;
            root /homework;
            index index.html;
          }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;';
